dictionary = {
    'a': ["Alive: (of a person, animal, or plant) living, not dead.","Avid: having or showing a keen interest in or enthusiasm for something.","Abecedarian: A person who is learning the letters of the alphabet.","Affable: Pleasantly easy to approach and to talk to; friendly; cordial; warmly polite","Adventurous: Inclined or willing to engage in adventures; enjoying adventures.","Acerbic: Sour or astringent in taste","Adept: Very skilled or proficient at something.","Admirable: Arousing or deserving respect and approval.","Angelic: (of a person) exceptionally beautiful, innocent, or kind.","Animation: Animation is the method that encompasses myriad filmmaking techniques, by which still images are manipulated to create moving images."],
    'b': ["Balmy: Characterized by pleasantly warm weather.","Brave: Ready to face and endure danger or pain; showing courage.","Beautiful: Pleasing the senses or mind aesthetically.","Benevolent: Well meaning and kindly.","Baggy: (of clothing) loose and hanging in folds.","Beat: Strike (a person or an animal) repeatedly and violently so as to hurt or injure them, typically with an implement such as a club or whip.","Blessed: Made holy; consecrated.","Bashful: Reluctant to draw attention to oneself; shy.","Banal: So lacking in originality as to be obvious and boring.","Beaming: Smiling broadly; grinning."],
    'c': ["Clean: Free from dirt, marks, or stains.","Clear: Easy to perceive, understand, or interpret.","Capable: Having the ability, fitness, or quality necessary to do or achieve a specified thing.","Careful: Making sure of avoiding potential danger, mishap, or harm; cautious.","Civil: Relating to ordinary citizens and their concerns, as distinct from military or ecclesiastical matters.","Complex: Consisting of many different and connected parts.","Content: In a state of peaceful happiness.","Charming: Very pleasant or attractive.","Clever: Quick to understand, learn, and devise or apply ideas; intelligent.","Certain: Able to be firmly relied on to happen or be the case."],
    'd': ["Daily: Done, produced, or occurring every day or every weekday.","Dandy: A man unduly concerned with looking stylish and fashionable.","Dally: Act or move slowly.","Daffy: Silly; mildly eccentric.","Dazed: Unable to think or react properly; bewildered.","Davit: A small crane on board a ship, especially one of a pair for suspending or lowering a lifeboat.","Damar: Resin obtained from any of a number of tropical, chiefly Indo-Malaysian trees, used to make varnish.","Daric: A gold coin and monetary unit of ancient Persia.","Doubt: A feeling of uncertainty or lack of conviction.","Damp: Moisture diffused through the air or a solid substance or condensed on a surface, typically with detrimental or unpleasant effects."],
    'e': ["Ease: Absence of difficulty or effort.","Eager: Strongly wanting to do or have something.","Earn: Obtain (money) in return for labour or services.","Easily: Without difficulty or effort.","Easy: Achieved without great effort; presenting few difficulties.","Easygoing: Relaxed and tolerant in attitude or manner.","Ecstasy: An overwhelming feeling of great happiness or joyful excitement.","Educate: Give intellectual, moral, and social instruction to (someone), typically at a school or university.","Efficient: (of a system or machine) achieving maximum productivity with minimum wasted effort or expense.","Effective: Successful in producing a desired or intended result."],
    'f': ["Fable: A story about supernatural or extraordinary persons or incidents; legend","Faced: Having a face or expression of a specified kind.","Facer: A sudden difficulty.","Faces: The front part of a person's head from the forehead to the chin, or the corresponding part in an animal.","Facet: One side of something many-sided, especially of a cut gem.","Facia: A detachable covering for the front part of a mobile phone.","Fabled: Famous, especially by reputation.","Fabler: A writer of fables; a fabulist; a dealer in untruths or falsehoods.","Fabric: Cloth or other material produced by weaving or knitting fibres.","Facade: The principal front of a building, that faces on to a street or open space."],
    'g': ["Gain: Obtain or secure (something wanted or desirable).","Giddy: Having a sensation of whirling and a tendency to fall or stagger; dizzy.","Gaudy: Extravagantly bright or showy, typically so as to be tasteless.","Giant: An imaginary or mythical being of human form but superhuman size.","Gate: A hinged barrier used to close an opening in a wall, fence, or hedge.","Gaffe: An unintentional act or remark causing embarrassment to its originator; a blunder.","Gale: A very strong wind.","Goofy: Foolish or harmlessly eccentric.","Gabby: Excessively or annoyingly talkative.","Gamut: The complete range or scope of something."],
    'h': ["Happiness:  A state of well-being that encompasses living a good life, one with a sense of meaning and deep contentment.","Hair: The mass of thin thread-like structures on the head of a person, or any of these structures that grow out of the skin of a person or animal","Hardy: Capable of enduring difficult conditions; robust.","Handy: Convenient to handle or use; useful.","Heavy: Of great weight; difficult to lift or move.","Halcyon: Denoting a period of time in the past that was idyllically happy and peaceful.","Hadji: A Muslim who has been to Mecca as a pilgrim.","Hamza: (in Arabic script) a symbol representing a glottal stop.","Hammy: (of acting or an actor) exaggerated or over-theatrical.","Haggard: Looking exhausted and unwell, especially from fatigue, worry, or suffering."],
    'i': ["Index: (in a book or set of books) an alphabetical list of names, subjects, etc. with reference to the pages on which they are mentioned.","Image: A representation of the external form of a person or thing in art.","Inlet: A small arm of the sea, a lake, or a river.","Igloo: An igloo also known as a snow house or snow hut, is a type of shelter built of suitable snow.","Ideal: Satisfying one's conception of what is perfect; most suitable.","Idiom: A group of words established by usage as having a meaning not deducible from those of the individual words (e.g. over the moon, see the light ).","Ichor: The fluid that flows like blood in the veins of the gods.","Icily: In an unfriendly way that shows no emotion","Idols: An image or representation of a god used as an object of worship.","Ilium: The large broad bone forming the upper part of each half of the pelvis."],
    'j': ["Jackpot: A large cash prize in a game or lottery, especially one that accumulates until it is won.","Jack: A device for lifting heavy objects, especially one for raising the axle of a motor vehicle off the ground so that a wheel can be changed or the underside inspected.","Jaded: Bored or lacking enthusiasm, typically after having had too much of something.","Jazzy: Of, resembling, or in the style of jazz.","Jewel: A precious stone, typically a single crystal or piece of a hard lustrous or translucent mineral cut into shape with flat facets or smoothed and polished for use as an ornament.","Jaunt: A short excursion or journey made for pleasure.","Jab: Poke roughly or quickly, especially with something sharp or pointed.","Jabber: Talk in a rapid, excited, and often incomprehensible way.","Jiffy: A very short time; a moment.","Jacky: An Aboriginal person."],
    'k': ["Key: A small piece of shaped metal with incisions cut to fit the wards of a particular lock, which is inserted into a lock and turned to open or close it.","Kennel: A kennel is a structure or shelter for dogs.","Kit: A set of articles or equipment needed for a specific purpose.","Knee: The knee is the largest joint in the body, and one of the most easily injured.","Keyboard: A panel of keys that operate a computer or typewriter.","Knot: A fastening made by looping a piece of string, rope, or something similar on itself and tightening it.","Knob: A rounded lump or ball, especially at the end or on the surface of something.","Kiwi: Kiwifruit or Chinese gooseberry is the edible berry of several species of woody vines in the genus Actinidia.","Kettle: A container or device in which water is boiled, having a lid, spout, and handle.","Kelp: Kelps are large brown algae or seaweeds that make up the order Laminariales."],
    'l': ["Lean: Be in or move into a sloping position.","Level: A horizontal plane or line with respect to the distance above or below a given point.","Lace: Lace is a delicate fabric made of yarn or thread in an open weblike pattern, made by machine or by hand.","Late: Doing something or taking place after the expected, proper, or usual time.","Laudable: (of an action, idea, or aim) deserving praise and commendation.","Lavish: Sumptuously rich, elaborate, or luxurious.","Lucky: Having, bringing, or resulting from good luck.","Lame: (especially of an animal) unable to walk without difficulty as the result of an injury or illness affecting the leg or foot.","Lanky: (of a person) ungracefully thin and tall","Lute: A lute is any plucked string instrument with a neck and a deep round back enclosing a hollow cavity, usually with a sound hole or opening in the body."],
    'm': ["Magnanimous: Generous or forgiving, especially towards a rival or less powerful person.","Majestic: Having or showing impressive beauty or scale.","Major: Important, serious, or significant.","Magnificent: Extremely beautiful, elaborate, or impressive.","Magical: Relating to, using, or resembling magic.","Mad: Very enthusiastic about someone or something.","Mean: Intend to convey or refer to (a particular thing); signify.","Master: Having or showing very great skill or proficiency.","Meet: Arrange or happen to come into the presence or company of (someone).","Malleable: (of a metal or other material) able to be hammered or pressed into shape without breaking or cracking."],
    'n': ["Neat: Arranged in a tidy way; in good order.","Nice: Giving pleasure or satisfaction; pleasant or attractive.","Naive: (of a person or action) showing a lack of experience, wisdom, or judgement.","Narrow: Having a small distance from one side to the other, especially in comparison with the length","Nascent: (especially of a process or organization) just coming into existence and beginning to display signs of future potential.","New: Produced, introduced, or discovered recently or now for the first time; not existing before.","Niche: A comfortable or suitable position in life or employment.","Nimble: Quick and light in movement or action; agile.","Nirvana: (in Buddhism) a transcendent state in which there is neither suffering, desire, nor sense of self, and the subject is released from the effects of karma and the cycle of death and rebirth. It represents the final goal of Buddhism.","Nonchalant: (of a person or manner) feeling or appearing casually calm and relaxed; not displaying anxiety, interest, or enthusiasm."],
    'o': ["Oasis: A fertile spot in a desert, where water is found.","Offer: Present or proffer (something) for (someone) to accept or reject as desired.","Obtain: Get, acquire, or secure (something).","Oblique: Neither parallel nor at right angles to a specified or implied line; slanting.","Oakum: Loose fibre obtained by untwisting old rope, used especially in caulking wooden ships.","Onset: The beginning of something, especially something unpleasant.","Oatmeal: Oatmeal is a preparation of oats that have been de-husked, steamed, and flattened, or a coarse flour of hulled oat grains that have either been milled, rolled, or steel-cut.","Oblong: A rectangular object or flat figure with unequal adjacent sides.","Obvious: Easily perceived or understood; clear, self-evident, or apparent.","Obsess: Preoccupy or fill the mind of (someone) continually and to a troubling extent."],
    'p': ["Patient: Able to accept or tolerate delays, problems, or suffering without becoming annoyed or anxious.","Prize: A thing given as a reward to the winner of a competition or in recognition of an outstanding achievement.","Pragmatics: Pragmatics is the study of how context contributes to meaning.","Paramount: more important than anything else; supreme.","Patience: The capacity to accept or tolerate delay, problems, or suffering without becoming annoyed or anxious.","Prime: Of first importance; main.","Pleasant: Giving a sense of happy satisfaction or enjoyment.","Persistent: Continuing firmly or obstinately in an opinion or course of action in spite of difficulty or opposition.","Plentiful: Existing in or yielding great quantities; abundant.","Palpable: (of a feeling or atmosphere) so intense as to seem almost tangible."],
    'q': ["Quiz","Quit","Quest","Queue","Quiet","Quite","Quote","Quint","Quill","Quail","Qualm","Quick"],
    'r': ["Rat","Rail","Rabbit","Rest","Ring","Rent","Rift","Rope","Rug","Rooster","Reverie","Rotation"],
    's': ["Self","Salt","Sky","Silk","Seed","Soap","Sauce","Stone","Shaft","Soul","Stunt","Stilt"],
    't': ["Tub","Tot","Tiger","Thief","Toss","Top","Thigh","Thud","Trough","Trash","Terrace","Thought"],
    'u': ["Unique","Unity","Ultimate","Unabashed","Unbiased","Unafraid","Unassuming","Unbelievable","Unconditional","Universal","Unconventional","Ubiquitous"],
    'v': ["Versatile","Vivacious","Vigilant","Venture","Vigorous","Visionary","Vapid","Voracious","Vacate","Valor","Vice","Vain"],
    'w': ["Wacky","Waffle","Waive","Waste","Wander","Waltz","White","Wager","Waiter","Waken","Weave","Waggish"],
    'x': ["Xylophone","Xerox","Xenophobia","Xebec","Xenial","Xanthic","Xystus","Xylene","Xanthous","Xanthate","Xenogamy","Xenolith"],
    'y': ["Yacht","Yawn","Yearn","Yell","Yeah","Yawp","Yoke","Yummy","Yawl","Yore","Yearly","Yogi"],
    'z': ["Zany","Zephyr","Zebra","Zappy","Zigzag","Zenith","Zesty","Zeal","Zarf","Zingy","Zilch","Zealous"]
}

def search_words(letter):
    return dictionary.get(letter.lower())

while True:
    user_input = input("Enter an alphabet to get its corresponding words ( or 'quit' to quit): ")
    
    if user_input == "quit":
        print("GoodBye___Thank You")
        break

    words = search_words(user_input)
    print("\n",str(words).replace('[',' ').replace(']',' ').replace("\'",' '),"\n")